TAX_CODES = {
    "CITYER": "City Employer Tax",
    "CITYWT": "City W/H",
    "CNTY1EE": "County 1 Employee",
    "CNTYER": "County Employer Tax",
    "CNTYSP1EE": "County Special 1 Employee",
    "CNTYSP2EE": "County Special 2 Employee",
    "CNTYSP3EE": "County Special 3 Employee",
    "CNTYWT": "County W/H",
    "FEDBU": "Federal Backup Withholding",
    "FEDEIC": "EIC",
    "FEDWT": "Federal W/H",
    "FUTAER": "FUTA Employer",
    "HEAD": "Occupational Tax",
    "LOCMISC1EE": "Local Miscellaneous 1 Employee",
    "LOCMISCEE": "Local Miscellaneous Employee Tax",
    "LOCSPEC1EE": "Local Special 1 Employee",
    "LOCSPEC2EE": "Local Special 2 Employee",
    "LOCSPEC3EE": "Local Special 3 Employee",
    "MEDEE": "Medicare",
    "MEDER": "Medicare Employer",
    "MENTAL": "Mental Health Tax",
    "SCHDIST": "School District",
    "SDI1EE": "State Disability 1 Employee",
    "SDI1ER": "State Disability 1 Employer",
    "SDIEE": "SDI EE",
    "SDIER": "State Disability Insurance Employer",
    "SOCSECEE": "Social Security",
    "SOCSECER": "Social Security Employer",
    "STATEWT": "State W/H",
    "STEIC": "State Advanced Earned Income Credit",
    "STMISC1EE": "State Miscellaneous 1 Employee",
    "STMISC2EE": "State Miscellaneous 2 Employee",
    "STMISC4EE": "State Miscellaneous 4 Employee",
    "STMISCEE": "State Miscellaneous Employee",
    "STMISCER": "State Miscellaneous Employer",
    "STSPEC1EE": "State Special 1 Employee",
    "STSPEC1ER": "State Special 1 Employer",
    "STSPEC2EE": "State Special 2 Employee",
    "STSPEC2ER": "State Special 2 Employer",
    "STSPEC3EE": "State Special 3 Employee",
    "STSPEC3ER": "State Special 3 Employer",
    "SUI1EE": "State Unemployment 1 Employee",
    "SUI1ER": "State Unemployment 1 Employer",
    "SUI2EE": "State Unemployment 2 Employee",
    "SUI2ER": "State Unemployment 2 Employer",
    "SUI3EE": "State Unemployment 3 Employee",
    "SUI3ER": "State Unemployment 3 Employer",
    "SUIEE": "SUI EE",
    "SUIER": "State Unemployment Insurance Employer",
    "WRKCOMPEE": "Workers Compensation Employee",
    "WRKCOMPER": "Workers Compensation Employer"
}
